CREATE DATABASE cadastro;

\c cadastro;

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE posts (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    conteudo TEXT NOT NULL
);
INSERT INTO users (name, email) VALUES 
    ('Thiago Ferreira', 'thiago.ferreira@email.com'),
    ('Marcelo Carboni', 'marcelo.carboni@email.com'),
    ('Eduardo Correia', 'eduardo.correia@email.com'),
    ('Felipe Santos', 'felipe.santos@email.com');
    
INSERT INTO users (name, email) VALUES 
    ('Lucas Almeida', 'lucas.almeida@email.com'),
    ('Ana Costa', 'ana.costa@email.com'),
    ('Carlos Pereira', 'carlos.pereira@email.com'),
    ('Juliana Lima', 'juliana.lima@email.com'),
    ('Roberta Souza', 'roberta.souza@email.com'),
    ('Mateus Oliveira', 'mateus.oliveira@email.com'),
    ('Patrícia Martins', 'patricia.martins@email.com'),
    ('Giovanni Ribeiro', 'giovanni.ribeiro@email.com'),
    ('Rafaela Pinto', 'rafaela.pinto@email.com'),
    ('Ricardo Mendes', 'ricardo.mendes@email.com'),
    ('Vanessa Rocha', 'vanessa.rocha@email.com'),
    ('André Barbosa', 'andre.barbosa@email.com'),
    ('Fernanda Silva', 'fernanda.silva@email.com'),
    ('Bruna Costa', 'bruna.costa@email.com'),
    ('Rodrigo Alves', 'rodrigo.alves@email.com'),
    ('Luciana Martins', 'luciana.martins@email.com'),
    ('Carlos Augusto', 'carlos.augusto@email.com'),
    ('Mariana Pereira', 'mariana.pereira@email.com'),
    ('João Vitor', 'joao.vitor@email.com'),
    ('Tatiane Nunes', 'tatiane.nunes@email.com'),
    ('Juliano Costa', 'juliano.costa@email.com'),
    ('Larissa Souza', 'larissa.souza@email.com'),
    ('Gustavo Lima', 'gustavo.lima@email.com'),
    ('Sofia Rocha', 'sofia.rocha@email.com'),
    ('Renato Carvalho', 'renato.carvalho@email.com'),
    ('Helena Martins', 'helena.martins@email.com'),
    ('Ricardo Souza', 'ricardo.souza@email.com'),
    ('Lúcia Freitas', 'lucia.freitas@email.com'),
    ('Tiago Almeida', 'tiago.almeida@email.com'),
    ('Isabela Barbosa', 'isabela.barbosa@email.com'),
    ('Rodrigo Santos', 'rodrigo.santos@email.com'),
    ('Paula Oliveira', 'paula.oliveira@email.com'),
    ('Vitor Costa', 'vitor.costa@email.com'),
    ('Cristiane Silva', 'cristiane.silva@email.com'),
    ('Paulo Henrique', 'paulo.henrique@email.com'),
    ('Amanda Rodrigues', 'amanda.rodrigues@email.com'),
    ('Ricardo Rocha', 'ricardo.rocha@email.com'),
    ('Beatriz Martins', 'beatriz.martins@email.com'),
    ('Daniel Lima', 'daniel.lima@email.com'),
    ('Marcos Silva', 'marcos.silva@email.com'),
    ('Gabriela Alves', 'gabriela.alves@email.com'),
    ('Felipe Oliveira', 'felipe.oliveira@email.com'),
    ('Tatiane Costa', 'tatiane.costa@email.com'),
    ('Adriano Nascimento', 'adriano.nascimento@email.com'),
    ('Simone Souza', 'simone.souza@email.com'),
    ('Aline Freitas', 'aline.freitas@email.com'),
    ('Diego Pereira', 'diego.pereira@email.com'),
    ('Paula Ribeiro', 'paula.ribeiro@email.com'),
    ('Mariana Souza', 'mariana.souza@email.com'),
    ('Breno Lima', 'breno.lima@email.com'),
    ('Alana Costa', 'alana.costa@email.com'),
    ('Eduarda Santos', 'eduarda.santos@email.com');

INSERT INTO posts (name, conteudo) VALUES 
    ('Thiago Ferreira', 'Post de banco de dados.'),
    ('Marcelo Carboni', 'Post sobre html e css.'),
    ('Eduardo Correia', 'Post sobre Front-End.'),
    ('Felipe Santos', 'Post sobre Back-End.');

INSERT INTO posts (name, conteudo) VALUES 
    ('Lucas Almeida', 'Post sobre JavaScript e frameworks modernos.'),
    ('Ana Costa', 'Post sobre CSS Grid e Flexbox.'),
    ('Carlos Pereira', 'Post sobre acessibilidade na web.'),
    ('Juliana Lima', 'Post sobre design responsivo.'),
    ('Roberta Souza', 'Post sobre performance de websites.'),
    ('Mateus Oliveira', 'Post sobre banco de dados NoSQL.'),
    ('Patrícia Martins', 'Post sobre otimização de código JavaScript.'),
    ('Giovanni Ribeiro', 'Post sobre GraphQL e suas vantagens.'),
    ('Rafaela Pinto', 'Post sobre desenvolvimento mobile.'),
    ('Ricardo Mendes', 'Post sobre testes automatizados.'),
    ('Vanessa Rocha', 'Post sobre segurança em aplicações web.'),
    ('André Barbosa', 'Post sobre React e hooks.'),
    ('Fernanda Silva', 'Post sobre APIs RESTful.'),
    ('Bruna Costa', 'Post sobre integração contínua.'),
    ('Rodrigo Alves', 'Post sobre Git e controle de versão.'),
    ('Luciana Martins', 'Post sobre MVC em aplicações web.'),
    ('Carlos Augusto', 'Post sobre TypeScript e suas vantagens.'),
    ('Mariana Pereira', 'Post sobre desenvolvimento ágil.'),
    ('João Vitor', 'Post sobre WebSockets e comunicação em tempo real.'),
    ('Tatiane Nunes', 'Post sobre boas práticas de programação.'),
    ('Juliano Costa', 'Post sobre arquitetura de microsserviços.'),
    ('Larissa Souza', 'Post sobre técnicas de SEO.'),
    ('Gustavo Lima', 'Post sobre PWA (Progressive Web Apps).'),
    ('Sofia Rocha', 'Post sobre integração de APIs externas.'),
    ('Renato Carvalho', 'Post sobre Redux e gerenciamento de estado.'),
    ('Helena Martins', 'Post sobre GitHub Actions para CI/CD.'),
    ('Ricardo Souza', 'Post sobre Docker e containers.'),
    ('Lúcia Freitas', 'Post sobre criação de interfaces com Figma.'),
    ('Tiago Almeida', 'Post sobre frameworks de teste JavaScript.'),
    ('Isabela Barbosa', 'Post sobre VUE.js e seu ecossistema.'),
    ('Rodrigo Santos', 'Post sobre Elasticsearch e busca avançada.'),
    ('Paula Oliveira', 'Post sobre MongoDB e modelagem de dados.'),
    ('Vitor Costa', 'Post sobre programação funcional em JavaScript.'),
    ('Cristiane Silva', 'Post sobre a importância de design UX/UI.'),
    ('Paulo Henrique', 'Post sobre programação orientada a objetos.'),
    ('Amanda Rodrigues', 'Post sobre CI/CD com Jenkins.'),
    ('Ricardo Rocha', 'Post sobre cloud computing e AWS.'),
    ('Beatriz Martins', 'Post sobre optimização de imagens para web.'),
    ('Daniel Lima', 'Post sobre Bootstrap e desenvolvimento front-end.'),
    ('Marcos Silva', 'Post sobre JWT (JSON Web Token) e autenticação.'),
    ('Gabriela Alves', 'Post sobre ferramentas de depuração JavaScript.'),
    ('Felipe Oliveira', 'Post sobre Angular e seu ecossistema.'),
    ('Tatiane Costa', 'Post sobre frameworks de back-end: Express vs Koa.'),
    ('Adriano Nascimento', 'Post sobre Micro Frontends.'),
    ('Simone Souza', 'Post sobre AR (Realidade Aumentada) na web.'),
    ('Aline Freitas', 'Post sobre técnicas de refatoração de código.'),
    ('Diego Pereira', 'Post sobre segurança em APIs RESTful.'),
    ('Paula Ribeiro', 'Post sobre a evolução do ECMAScript.'),
    ('Mariana Souza', 'Post sobre Machine Learning no Front-End.'),
    ('Breno Lima', 'Post sobre a arquitetura de aplicações Serverless.'),
    ('Alana Costa', 'Post sobre MongoDB vs SQL Databases.'),
    ('Eduarda Santos', 'Post sobre práticas de desenvolvimento sustentável.');
